version: "3.8"
services:
  dcs-postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "5432:5432"